language: node_js
node_js:
  - 14
script:
  - echo '*** Starting build ***'
  - echo 'install dependencies'
  - npm install
  - echo 'Running test'
  - npm test
deploy:
  provider: heroku
  api_key: 019a7dc0-466b-4a59-8e1b-c36d7b53e925
  app: Test-CI/CD-App
  strategy: git
  run:
  - restart
